name: EasyBan
main: uk.org.whoami.easyban.EasyBan
version: 3.0.5 B:25
description: 'Ban people/subnets/countries from "offline" Servers'
authors:
- whoami
- Fishrock123
website: 'http://dev.bukkit.org/server-mods/easyban/'
softdepend: [GeoIPTools]
commands:
    ekick:
        description: Kick player
        usage: /ekick playername
    ehistory:
        description: List all ips of a player
        usage: /elistips playername
    ealternative:
        description: Get alternative nicknames of a player
        usage: /ealternative playername
    eban:
        description: Ban player
        usage: /eban playername [reason] [time]
    eunban:
        description: Unban player
        usage: /eunban playername
    ebaninfo:
        description: Get informations about a ban
        usage: /ebaninfo playername/subnet
    elistbans:
        description: List all banned players
        usage: /elistbans
    elisttmpbans:
        description: List all temporary bans
        usage: /elisttmpbans
    ebansubnet:
        description: Ban a whole subnet
        usage: /esubnetban a.b.c.d/w.x.y.z [reason]
    eunbansubnet:
        description: Unban a whole subnet
        usage: /esubnetunban a.b.c.d/w.x.y.z
    elistsubnets:
        description: List all banned subnets
        usage: /elistsubnets
    ebancountry:
        description: Ban a country
        usage: /ebancountry countrycode
    eunbancountry:
        description: Unban a country
        usage: /eunbancountry countrycode
    elistcountries:
        description: Show all banned countries
        usage: /elistcountries
    ewhitelist:
        description: Whitelist players from range bans
        usage: /ewhitelist playername
    eunwhitelist:
        description: Unwhitelist a player
        usage: /eunwhitelist playername
    elistwhite:
        description: Show whitelisted players
        usage: /elistwhite
    ereload:
        description: Reload configuration file
        usage: /ereload
permissions:
    easyban.*:
        description: Gives access to all EasyBan commands
        children:
            easyban.ekick: true
            easyban.ehistory: true
            easyban.ealternative: true
            easyban.eban: true
            easyban.eunban: true
            easyban.ebaninfo: true
            easyban.elistbans: true
            easyban.elisttmpbans: true
            easyban.ebansubnet: true
            easyban.eunbansubnet: true
            easyban.elistsubnets: true
            easyban.ebancountry: true
            easyban.eunbancountry: true
            easyban.elistcountries: true
            easyban.ewhitelist: true
            easyban.eunwhitelist: true
            easyban.elistwhite: true
    easyban.ekick:
        description: Allows you to kick a user
        default: op
    easyban.ehistory:
        description: List all ips of a player
        default: op
    easyban.ealternative:
        description: Get alternative nicknames of a player
        default: op
    easyban.eban:
        description: Ban player
        default: op
    easyban.eunban:
        description: Unban player
        default: op
    easyban.ebaninfo:
        description: Get informations about a ban
        default: op
    easyban.elistbans:
        description: List all banned players
        default: op
    easyban.elisttmpbans:
        description: List all temporary bans
        default: op
    easyban.ebansubnet:
        description: Ban a whole subnet
        default: op
    easyban.eunbansubnet:
        description: Unban a whole subnet
        default: op
    easyban.elistsubnets:
        description: List all banned subnets
        default: op
    easyban.ebancountry:
        description: Ban a country
        default: op
    easyban.eunbancountry:
        description: Unban a country
        default: op
    easyban.elistcountries:
        description: Show all banned countries
        default: op
    easyban.ewhitelist:
        description: Whitelist players from range bans
        default: op
    easyban.eunwhitelist:
        description: Unwhitelist a player
        default: op
    easyban.elistwhite:
        description: Show whitelisted players
        default: op
    easyban.admin.protected:
        description: protectects the player from kicks/bans
        default: op